stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - Training_Batch_Files/training_batch.csv
    outs:
    - data/raw/training_batch.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/training_batch.csv
    outs:
    - data/processed/training_data/train.csv
    - data/processed/testing_data/test.csv
  train_evaluate:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/training_data/train.csv
    - data/processed/testing_data/test.csv 
    - src/train_evaluate.py
    params:
    - estimators.DecisionTreeClassifier.params.criterion    
    - estimators.DecisionTreeClassifier.params.max_depth
    - estimators.DecisionTreeClassifier.params.min_samples_leaf
    - estimators.DecisionTreeClassifier.params.min_samples_split
    
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - src/models/model.joblib
